/* AUTO-GENERATED DO NOT EDIT */
#define FIELD_TYPE_USED_CHOICE

#define FIELD_TYPE_USED_UINT

#define FIELD_TYPE_USED_GPIOPIN

#define FIELD_TYPE_USED_GPIOLEVEL

#if (defined(CONFIG_SI7021)) || (defined(CONFIG_TSL2561)) || (defined(CONFIG_BME280))
#define FIELD_TYPE_USED_I2CADDR
#endif


#define FIELD_TYPE_USED_BOOL

#define FIELD_TYPE_USED_STRING
