wifi:
  ssid: <SSID>
  pass: <password>
mqtt:
  host: <MQTT Host>
# port: # <Optional Port>
# user: # <Optional user>
# pass: # <Optional password>
#gpiox: # Optional GPIO Extender
# num:  # Number of GPIO extenders 0 - 4
# sda:  # Pin used for I2C SDA
# scl:  # Pin used for I2C SCL  
thing:
  profile: 
    ds18x20:
      - pin: 14
        id: sensor
    relay:
      - pin: 13
        level: 1
        id: relay
    switch:
      - pin: 0
        type: momemetary
        relay: relay
    led:
      - pin: 12
    bme280:
      - sda: 4
        scl: 5
        name: "Example BME280"
    si7021:
      - sda: 4
        scl: 5
        name: "Example SI7021"