- title: Device
  name: thing
  variables:
  - title: ID
    name: id
    type: device_id
  - title: Description
    name: desc
    type: string
- title: Wireless Network
  name: wifi
  variables:
  - - title: Wireless Network
      name: ssid
      type: username
    - title: Passphrase
      name: pass
      type: password
- title: MQTT
  name: mqtt
  variables:
  - - title: Hostname
      name: host
      type: hostname
    - title: Port (default 1883)
      name: port
      type: port
  - - title: Username (optional)
      name: user
      type: username
    - title: Passphrase (optional)
      name: pass
      type: password
- title: Logging
  name: log
  variables:
  - - title: Hostname
      name: host
      type: hostname
    - title: Port
      name: port
      type: port
  - title: Enable
    name: enable
    type: checkbox
