name: Build
on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [flash1mb, flash4mb, esp32]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Determine SDK and version
        id: sdk
        run: |
          if [ "${{ matrix.build_type }}" == "esp32" ]; then
            echo "repo=espressif/esp-idf" >> $GITHUB_OUTPUT
            echo "ref=release/v4.4" >> $GITHUB_OUTPUT
          else
            echo "repo=espressif/ESP8266_RTOS_SDK" >> $GITHUB_OUTPUT
            echo "ref=release/v3.3" >> $GITHUB_OUTPUT
          fi

      - name: Checkout SDK
        uses: actions/checkout@v3
        if: matrix.build_type != 'esp32'
        with:
          repository: ${{ steps.sdk.outputs.repo }}
          ref: ${{ steps.sdk.outputs.ref }}
          path: sdk
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Setup environment
        run: |
          cd sdk
          ./install.sh
      
      - name: Install python requirements
        run: |
          source sdk/export.sh
          pip install -r requirements.txt

      # - name: Patch SDK for pthread link issue
      #   run: |
      #     cd sdk
      #     git apply ../esp8266_rtos_sdk_v3_4.patch

      - name: Build
        run: |
          cp sdkconfig.${{ matrix.build_type }} sdkconfig
          source sdk/export.sh
          idf.py build otagen
      
      - name: Store images
        uses: actions/upload-artifact@v3
        with:
          name: esp8266-${{ matrix.build_type }}
          path: |
            build/homething*
