name: Build
on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [esp8266-flash1mb, esp8266-flash4mb, esp32]
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Load settings
        id: settings
        run: |
          cat ".github/workflows/settings.${{ matrix.build_type }}" >> $GITHUB_OUTPUT

      - name: Checkout SDK
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.settings.outputs.repo }}
          ref: ${{ steps.settings.outputs.ref }}
          path: sdk
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Setup environment
        run: |
          cd sdk
          ./install.sh
      
      - name: Install python requirements
        run: |
          source sdk/export.sh
          pip install -r requirements.txt

      - name: Patch SDK for pthread link issue
        if:  steps.settings.outputs.patch == 'yes'
        run: |
          cd sdk
          git apply ../esp8266_rtos_sdk_v3_4.patch

      - name: Build
        run: |
          cp sdkconfig.${{ matrix.build_type }} sdkconfig
          source sdk/export.sh
          idf.py build otagen
      
      - name: Store images
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build_type }}
          path: |
            build/homething*
